### ISSUE TITLE
merge v2 branch in master

### ISSUE THREAD

**Issue by richlv** [ksyz/Net-Zabbix#1]
currently master branch uses 'user.authenticate' method, while v2 branch uses 'user.login' method.
user.login is supported in all version of zabbix, while user.authenticate is deprecated and removed in the latest versions. it would probably be best to merge v2 into master and go forward with a single branch only

**Comment by ksyz** [comment]
Many days later, in a distant past..
OK, I did switch the main branch to v2. It looks like some people forked the "legacy" master branch, so I will leave it as it is.
